MP12/gym_project/gym_admin/urls.py
from gym_app.views import home
from django.urls import path
from . import views

app_name = 'gym_admin'

urlpatterns = [
    path('', home, name='home'),
    path('users/', views.user_list, name='user_list'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),  
    path('users/delete/', views.delete_user, name='delete_user'), 

]

MP12/gym_project/gym_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.views import LogoutView

app_name = 'gym_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/editar', views.profile_edit, name='profile_edit'),
    # path('test-create/', views.test_create_user, name='test-create'),
]

MP12/gym_project/gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym_app.urls', namespace='gym_app')),
    path('gym_trainer/', include('gym_trainer.urls'), name='gym_trainer'),
    path('gym_admin/', include('gym_admin.urls'), name='gym_admin'),
    path('gym_gerent/', include('gym_gerent.urls'), name='gym_gerent'),
    path('gym_workouts/', include('gym_workouts.urls'), name='gym_workouts'),

]

MP12/gym_project/gym_trainer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from gym_app.views import home

app_name = 'gym_trainer'

urlpatterns = [
    path('', home, name='home'),
    path('entrenador/inici', home, name='home'),
    path('entrenador/crear_rutina', views.create_routine, name='create_routine'),
    path('rutines/', views.assign_schedule, name='assign_schedule'),
    path('routines/list', views.routine_list, name='routine_list'),
    path('routines/<int:routine_id>/edit/', views.edit_routine, name='edit_routine'),
    path('routines/<int:routine_id>/delete/', views.delete_routine, name='delete_routine'),
    path('routines/delete/schedule/', views.delete_schedule, name='delete_schedule'),

    # path('test-create/', views.test_create_user, name='test-create'),
]

MP12/gym_project/gym_workouts/urls.py
from gym_app.views import home
from django.urls import path
from . import views

app_name = 'gym_workouts'

urlpatterns = [
    path('', home, name='home'),
    path('select_subscription/', views.select_subscription, name='select_subscription'),
    path('workouts/', views.workouts, name='workouts'),
    path('enroll_user/', views.enroll_user, name='enroll_user'),
    path('leave_routine/', views.leave_routine, name='leave_routine'),
]

MP12/gym_project/gym_app/models.py
from django.contrib.auth.models import AbstractUser 
from django.db import models
from gym_workouts.models import Subscription

class User(AbstractUser ):
    ROLE_CHOICES = [
        ('admin', 'Administrador'),
        ('user', 'Usuari del Gimnàs'),
        ('trainer', 'Entrenador'),
        ('gerent', 'Gerent')
    ]
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    subscription = models.ForeignKey(Subscription, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = 'users'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    REQUIRED_FIELDS = ['role']
    USERNAME_FIELD = 'email'

MP12/gym_project/gym_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from gym_trainer.models import Schedule, Routine
from django import forms
from .models import User

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'role', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            if User.objects.filter(email=email).exists():
                raise ValidationError("Aquest correu ja está registrat.")
        except Exception as e:
            raise ValidationError("Aquest correu ja está registrat.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            if User.objects.filter(username=username).exists():
                raise ValidationError("Aquest nom d'usuari ja està agafat.")
        except Exception as e:
            raise ValidationError("Aquest nom d'usuari ja està agafat.")
        return username
        
class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [ 'username', 'email', 'first_name', 'last_name']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Afegim classes per  l'estil i plachefolders
        for fields in self.fields:
            self.fields[fields].widget.attrs.update({'class': 'form-control', 'placeholder': self.fields[fields].label})
            

MP12/gym_project/gym_app/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from gym_trainer.models import Schedule, Routine
from django.contrib import messages
from .forms import *

# Depenent del rol de l'usuari redirigim a una pàgina o un altre
@login_required
def home(request):
    context = {}
    if request.user.role == 'trainer':
        return redirect('gym_trainer:assign_schedule') 
    
    elif request.user.role == 'user':
        return redirect('gym_workouts:workouts')
    
    elif request.user.role == 'admin':
        return redirect('gym_admin:user_list')
    
    elif request.user.role == 'gerent':
        return redirect('gym_gerent:user_list')
    

    return render(request, 'home.html', context)


# Vista per registrar l'usuari
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Registre exitós.")
                return redirect('login')
            except Exception as e:
                print(f"Hi ha hagut un error: {str(e)}")
        else:
            messages.warning(request, "Hi han errors al formulari.")
    else:
        form = UserRegistrationForm()
    
    return render(request, 'register.html', {'form': form})


# Vista per loguejar un usuari
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            print(user)
            if user is not None:
                login(request, user)
                messages.success(request, 'Has iniciat sessió correctament!')
                return redirect('gym_app:home')
            else:
                messages.warning(request, 'ERROR: Credencials incorrectes.')
    else:
        form = UserLoginForm()
    return render(request, 'login.html', {'form': form})


# Logout
@login_required
def logout_view(request):
    logout(request)
    return redirect('gym_app:home')


# Vista per editar el perfil
@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'El perfil s\'ha actualitzat correctament.')
            return redirect('gym_app:home')
    else:
        form = UserUpdateForm(instance=request.user)
        
    return render(request, 'profile_edit.html', {'form': form, 'active_tab': "profile"})

MP12/gym_project/gym_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ca">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GymApp{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="{% static 'dist/bundle.css' %}" rel="stylesheet">
    <link href="{% static 'dist/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-purple shadow">
        <div class="container">
            <a class="navbar-brand" href="{% url 'gym_app:home' %}">GymApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'gym_app:home' %}">Inici</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="trainerDropdown">
                                {% if user.role == 'trainer' %}
                                    <li><a class="dropdown-item" href="{% url 'gym_trainer:create_routine' %}">Crear Rutina</a></li>
                                    <li><a class="dropdown-item" href="{% url 'gym_trainer:routine_list' %}">Llistar Rutines</a></li>

                                {% elif user.role == 'user' %}
                                    <li><a class="dropdown-item" href="{% url 'gym_workouts:select_subscription' %}">Seleccionar Cuota</a></li>
                                
                                {% elif user.role == 'admin' %}
                                    <li><a class="dropdown-item" href="{% url 'gym_admin:user_list' %}">Llistat d'usuaris</a></li>


                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'gym_app:profile_edit' %}">Editar Perfil</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'gym_app:logout' %}">Tancar sessió</a></li>

                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'gym_app:login' %}">Iniciar sessió</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Messages -->
    {% if messages %}
    <div class="container mt-4">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Main content -->
    <div class="container my-5">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

MP12/gym_project/gym_app/templates/login.html
{% extends 'base.html' %} 
{% block title %}Iniciar Sessió - GymApp{% endblock %} 
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow">
                <div class="card-header">
                    <i class="fas fa-sign-in-alt"></i> Iniciar Sessió
                </div>
                <div class="card-body">
                    <!-- Formulari d'inici de sessió -->
                    <form method="post">
                        {% csrf_token %} {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> {{ field }}
                            <div class="text-danger">{{ field.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 purple-btn">Iniciar Sessió</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MP12/gym_project/gym_app/templates/profile_edit.html
{% extends 'base.html' %} 
{% block title %}Editar perfil - GymApp{% endblock %} 
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow">
                <div class="card-header">
                    <i class="fas fa-sign-in-alt"></i> Editar perfil
                </div>
                <div class="card-body">
                    <!-- Formulari per editar el perfil -->
                    <form method="post">
                        {% csrf_token %} {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> {{ field }}
                            <div class="text-danger">{{ field.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn purple-btn">Desar canvis</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MP12/gym_project/gym_app/templates/register.html
{% extends 'base.html' %} {% block title %}Registre - GymApp{% endblock %} {% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow">
                <div class="card-header">
                    <i class="fas fa-sign-in-alt"></i> Registre
                </div>
                <div class="card-body">
                    <!-- Formulari per registrar un nou usuari-->
                    <form method="post">
                        {% csrf_token %} {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> {{ field }}
                            <div class="text-danger">{{ field.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-success w-100 purple-btn">Registrar-se</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}