MP12/gym_project/gym_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.views import LogoutView

app_name = 'gym_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/editar', views.profile_edit, name='profile_edit'),
    # path('test-create/', views.test_create_user, name='test-create'),
]

MP12/gym_project/gym_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym_app.urls', namespace='gym_app')),
    path('gym_trainer/', include('gym_trainer.urls'), name='gym_trainer'),
    path('gym_admin/', include('gym_admin.urls'), name='gym_admin'),
    path('gym_gerent/', include('gym_gerent.urls'), name='gym_gerent'),
    path('gym_workouts/', include('gym_workouts.urls'), name='gym_workouts'),

]

MP12/gym_project/gym_workouts/urls.py
from gym_app.views import home
from django.urls import path
from . import views

app_name = 'gym_workouts'

urlpatterns = [
    path('', home, name='home'),
    path('select_subscription/', views.select_subscription, name='select_subscription'),
    path('workouts/', views.workouts, name='workouts'),
    path('enroll_user/', views.enroll_user, name='enroll_user'),
    path('leave_routine/', views.leave_routine, name='leave_routine'),
]

MP12/gym_project/gym_workouts/models.py
from django.contrib.auth.models import User
from gym_trainer.models import Schedule, Routine
from django.conf import settings
from django.db import models

class Subscription(models.Model):
    PLAN_CHOICES = [
        ('1_routine', '1 rutina a la setmana - 15€ al mes'),
        ('3_routines', '3 rutines a la setmana - 30€ al mes'),
        ('unlimited', 'Rutines il·limitades - 50€ al mes'),
    ]

    name = models.CharField(max_length=50, choices=PLAN_CHOICES)
    price = models.FloatField()
    
    # Les rutines màximes, serà "None" si el pla és il·limitat
    max_routines = models.PositiveIntegerField(null=True, blank=True) 

    def __str__(self):
        return f"{self.get_name_display()} - {self.price}€"

MP12/gym_project/gym_workouts/forms.py
from gym_trainer.models import Schedule
from .models import Subscription
from django import forms

class SubscriptionForm(forms.Form):
    subscription = forms.ModelChoiceField(queryset=Subscription.objects.all(), empty_label="Selecciona una suscripción")


class EnrollForm(forms.Form):
    id = forms.IntegerField(widget=forms.HiddenInput())

MP12/gym_project/gym_workouts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from gym_trainer.models import Schedule, Routine
from .forms import SubscriptionForm, EnrollForm
from django.http import HttpResponse
from django.contrib import messages
from django.utils import timezone
from .models import Subscription
from datetime import timedelta

# Mostrem les rutines a les que l'usuari podría inscriure-se'n
@login_required
def workouts(request):
    routines = Routine.objects.all()
    hours = ['16', '17', '18', '19', '20', '21']
    schedule_data = {}

    # Data d'avui
    today = timezone.now().date()
    
    # Obtenim el dia de la setmana (0 = Dilluns, ..., 6 = Diumenge)
    current_weekday = today.weekday()

    # Definim els noms dels dies
    days_of_week = ['Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres']

    week_dates = []
    for i, day_name in enumerate(days_of_week):
        if i < 2:  # Dilluns i Dimarts han de ser de la setmana següent
            next_week_day = today + timedelta(days=(7 - current_weekday + i))
            week_dates.append(next_week_day.strftime("%d/%m"))
        else:  # Dimecres, Dijous i Divendres són de la setmana actual
            this_week_day = today - timedelta(days=current_weekday - i)
            week_dates.append(this_week_day.strftime("%d/%m"))

    # Combinem els dies de la setmana amb els dies numèrics
    days_with_dates = list(zip(days_of_week, week_dates))

    # Agafem les rutines programades
    for day, date in days_with_dates:
        for hour in hours:
            schedule_entry = Schedule.objects.filter(day=day, time=f"{hour}:00").first()
            if schedule_entry:
                schedule_data[f"{day}_{hour}"] = {
                    'schedule': schedule_entry,
                    'is_enrolled': request.user in schedule_entry.enrollments.all()
                }
            else:
                schedule_data[f"{day}_{hour}"] = None  

    return render(request, 'workouts.html', {
        'routines': routines,
        'days_with_dates': days_with_dates, 
        'hours': hours,
        'schedule_data': schedule_data,
        'user': request.user,
        'today': today.strftime("%d/%m"),  
    })



# Vista per seleccionar la subscripcio
@login_required
def select_subscription(request):
    subscriptions = Subscription.objects.all() 
    form = SubscriptionForm() 

    # Obtenim la subscripció actual si es que hi ha
    current_subscription = getattr(request.user, 'subscription', None) 

    # Guardem l'estat de la subscripció
    if current_subscription is not None:
        subscription_status = current_subscription.get_name_display()  
    else:
        subscription_status = "Cap"  

    # Utilitzem el formulari SuscriptionForm per canviar la subscripció
    if request.method == 'POST':
        form = SubscriptionForm(request.POST)  
        if form.is_valid():
            selected_subscription = form.cleaned_data['subscription']
            request.user.subscription = selected_subscription
            request.user.save()
            messages.success(request, f"Subscripció '{selected_subscription.get_name_display()}' assignada correctament!")
            return redirect('gym_workouts:home') 
        else:
            print(form.errors) 
            
    return render(request, 'select_subscription.html', {
        'form': form,
        'subscriptions': subscriptions,
        'subscription_status': subscription_status,  
    })


@login_required
def enroll_user(request):
    if request.method == 'POST':
        form = EnrollForm(request.POST)
        if form.is_valid():
            schedule_id = form.cleaned_data['id']
            schedule = get_object_or_404(Schedule, id=schedule_id)

            # Verifiquem que l'usuari tingui subscripció
            if not request.user.subscription:
                messages.warning(request, "Has de tenir una subscripció per inscriure't a rutines.")
                return redirect('gym_workouts:workouts')

            # Obtenim el màxim de rutines segons la subscripció de l'usuari
            max_routines = request.user.subscription.max_routines if request.user.subscription else 0

            # Si la subscripció és il·limitada
            if request.user.subscription and request.user.subscription.name == 'unlimited':
                max_routines = float('inf')  # Il·limitat

            # Comprovem que l'usuari es pot inscriure
            if schedule.count_enrolled() < 10 and request.user.enrolled_schedules.count() < max_routines:
                schedule.enrollments.add(request.user)
                messages.success(request, "T'has inscrit a la rutina correctament!")
            else:
                messages.warning(request, 'Ja no et pots inscriure!.')
        else:
            print(form.errors)  
            messages.warning(request, 'Hi ha hagut un error inesperat.')

    return redirect('gym_workouts:workouts')


    
# Vista per sortir d'una rutina
def leave_routine(request):
    if request.method == 'POST':
        schedule_id = request.POST.get('schedule_id')
        schedule = get_object_or_404(Schedule, id=schedule_id)
        
        if request.user in schedule.enrollments.all():
            schedule.enrollments.remove(request.user) 
            messages.success(request, "Has sortit de la rutina amb éxit.")
        else:
            messages.warning(request, "No estàs inscrit a aquesta rutina.")

    return redirect('gym_workouts:workouts')

MP12/gym_project/gym_workouts/templates/select_subscription.html
{% extends 'base.html' %}

{% block title %}
Selecciona tu Cuota - GymApp
{% endblock %}

{% block content %}
<style>
    textarea {
        resize: none; 
        width: 100%;
        height: 150px;  
    }

    input[type="text"] {
        resize: none; 
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow">
                <div class="card-header">
                    <i class="fas fa-edit"></i> Selecciona la teva quota
                </div>
                <div class="card-body">
                    <!-- Mostrem la suscripció acutal -->
                    <p>Tu suscripción actual: <strong>{{ subscription_status }}</strong></p>  
                    
                    <!-- Formulari per escollir una suscripció-->
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            <div class="text-danger">{{ field.errors }}</div>
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn purple-btn">Confirmar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MP12/gym_project/gym_workouts/templates/workouts.html
{% extends 'base.html' %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% load custom_filters %}
{% block content %}
<div class="container mt-5">
    <h2>Horari de Rutines</h2>

    <div class="table-responsive">
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <!-- A la capçalera mostrem "Hora" i els dies amb la data format dd/mm i "Avui" en cas que sigui avui-->
                    <th>Hora</th>
                    {% for day, date in days_with_dates %}
                        <th>
                            {% if date == today %}
                                (Avui) {{ day }} {{ date }}
                            {% else %}
                                {{ day }} {{ date }}
                            {% endif %}
                        </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>

                <!-- Mostrem el calendari de la setmana amb les rutines -->
                {% for hour in hours %}
                    <tr>
                        <td>{{ hour }}:00</td>
                        {% for day, date in days_with_dates %}
                            <td>
                                {% with key=day|add:"_"|add:hour %}
                                    {% if schedule_data|get_item:key %}
                                        {% with schedule=schedule_data|get_item:key %}
                                            <div class="d-flex flex-column align-items-center">
                                                <strong>{{ schedule.schedule.routine.name }}</strong>
                                                <!-- Mostrem les persones apuntades -->
                                                <p>
                                                    {{ schedule.schedule.enrollments.count }} / 10 persones apuntades 
                                                </p>

                                                <!-- Depenent de si l'usuari está inscrit o no mostrem Reservar o Cancelar reserva-->
                                                {% if not schedule.is_enrolled %}
                                                    <form method="POST" action="{% url 'gym_workouts:enroll_user' %}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="id" value="{{ schedule.schedule.id }}">
                                                        <button type="submit" class="btn btn-success btn-sm">Reservar</button>
                                                    </form>
                                                {% else %}
                                                    <form method="POST" action="{% url 'gym_workouts:leave_routine' %}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="schedule_id" value="{{ schedule.schedule.id }}">
                                                        <button type="submit" class="btn btn-danger btn-sm">Cancelar</button>
                                                    </form>
                                                {% endif %}
                                            </div>
                                        {% endwith %}
                                    {% else %}
                                        <!-- Si no hi han rutines assignades ho mostrem-->
                                        <p class="text-muted" style="font-style: italic;">No hi han rutines assignades</p>
                                    {% endif %}
                                {% endwith %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}